### ISSUE TITLE
Syntax Highlighting in Php Storm

### ISSUE THREAD

**Issue by msthzn** [adelf/idea-php-dotenv-plugin#23] opened 2018-07-07 07:16 UTC
Hello, first of all thx for plugin. Would you please add syntax highlighting in phpstorm. PhpStorm is one of the most popular u know, without syntax highlighting plugin is nothing in phpstorm :(

**Comment by jezmck** [comment] 2018-08-16 08:13
At the very least, a different colour for comments would be amazing.

**Comment by jezmck** [comment] 2018-08-16 08:18
This is a duplicate of #2.

**Closed** 2018-08-25 17:17 UTC
Labels: duplicate
